# File: .github/workflows/workflow.yml
name: Build and Deploy Application to Azure App Service

on: 
  push:
    branches:    
      - 'master'
  pull_request:   
      

env:
  AZURE_WEBAPP_NAME: dgart   
  AZURE_WEBAPP_PACKAGE_PATH: './dist/art-application'     
  NODE_VERSION: '14.x'                

jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - name: npm install, build, and test
      run: |
        # Build and test the project, then
        # deploy to Azure Web App.
        npm install
        npm run build --if-present
      working-directory: '.'
      
  deploy:
    name: Deploy
    needs: build
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    steps:
    - uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}  
